# Generated by Django 6.1 on 2026-10-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_id_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المستودع')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='العنوان / الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='location',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.warehouse', verbose_name='موقع التخزين'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.warehouse', verbose_name='موقع التخزين'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('product', 'condition', 'warehouse')},
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='location',
        ),
    ]
